config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('video.urls', namespace='video')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

video/urls.py
from django.urls import path
from video.apps import VideoConfig

from video.views import index, VideoListView, download_file

app_name = VideoConfig.name


urlpatterns = [
    path('', index, name="index"),
    path('download/<int:pk>/', download_file, name='download_file'),
    path('videos/', VideoListView.as_view(), name="videos"),
]

video/models.py
from django.db import models


class Video(models.Model):
    title = models.CharField(max_length=50, verbose_name='название')
    message = models.TextField(verbose_name='сообщение')
    video = models.FileField(upload_to='videos/', verbose_name='видео')
    create_time = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Видео'
        verbose_name_plural = 'Видео'

video/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.views.generic import ListView

from utils.utils import create_video_opencv, convert_to_h264
from video.models import Video


def index(request):
    message = str(request.GET.get('message', ''))
    result = create_video_opencv(message)
    # convert_to_h264(f'media/{result["path"]}')
    new_video = Video(title=result['title'], message=message, video=result['path'])
    new_video.save()
    context = {'object': new_video}
    return render(request, 'video/index.html', context)


def download_file(request, pk):
    video = Video.objects.get(pk=pk)
    response = HttpResponse(video.video, content_type='application/force-download')
    response['Content-Disposition'] = f'attachment; filename="{video.video.name}"'
    return response


class VideoListView(ListView):
    model = Video

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        print(queryset)
        return queryset

video/templates/video/index.html
<!DOCTYPE html>
{% load static %}
{% load my_tags %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<!--    <video width="400" controls>-->
<!--      <source src="{{object.video|mymedia}}" type="video/mp4">-->
<!--      Your browser does not support HTML5 video.-->
<!--    </video>-->

{% if object %}
Видео: {{ object.title}}  <a href="{% url 'video:download_file' object.pk %}">Скачать</a>
{% endif %}
<br>
<a href="{% url 'video:videos' %}">Все видео</a>
</body>
</html>

video/templates/video/video_list.html
<!DOCTYPE html>
{% load static %}
{% load my_tags %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% if object_list %}
    {% for object in object_list %}
        Видео: {{ object.title}}  <a href="{% url 'video:download_file' object.pk %}">Скачать</a>
        <br>
<!--    <video width="400" controls>-->
<!--      <source src="{{object.video|mymedia}}" type="video/mp4">-->
<!--      Your browser does not support HTML5 video.-->
<!--    </video>-->
    {% endfor %}
{% else %}
Нет видео
{% endif %}

</body>
</html>